config/routes.rb
Masterater::Application.routes.draw do
  get "betas/confirmation"
  resources :betas, :only => ["new","create"]

  get "rankings/global"
  get "rankings/friends"
  get "rankings/groups"
  match "rankings" => "rankings#index"

  resources :groups, :only => ["show"]

  resources :users, :only => ["show"]                          #admin_data

  match "/settings" => "users#settings"
  get "user/show"
  get "user/update_info"

  match "/about" => "home#about"
  match "/privacy" => "home#privacy"
  match "/battle_update" => "home#battle_update"
  match "/invite" => "home#invite"
  match "/invite_update" => "home#invite_update"

  match "/canvas" => "home#canvas"

  match "/battle" => "home#battle"

  root :to => "home#index"

  match "/auth/:provider/callback" => "sessions#create"

  match "/signout" => "sessions#destroy", :as => :signout

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships,:dependent => :destroy
  has_many :users, :through => :memberships

  def name_and_size
    self.name + ' (' + self.users.size.to_s + ')'
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.xml

  def index
    @groups = Group.all.sort{ |b,a| a.users.size <=> b.users.size}

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.xml
  def show
    @group = Group.find(params[:id])
    group_members = @group.users
    @group_size = group_members.size
    @group_average = (group_members.average(:score)) # / @group_size
    @group_win = group_members.inject (0) { |sum,user| sum + user.win }
    @group_loss = group_members.inject (0) { |sum,user| sum + user.loss }
    @top_females = group_members.female.top25
    @top_males = group_members.male.top25
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.xml
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.xml
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to(@group, :notice => 'Group was successfully created.') }
        format.xml  { render :xml => @group, :status => :created, :location => @group }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.xml
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to(@group, :notice => 'Group was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.xml
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to(groups_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :gid %><br />
    <%= f.text_field :gid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th>Gid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @groups.each do |group| %>
  <tr>
    <td><%= group.name %></td>
    <td><%= group.type %></td>
    <td><%= group.gid %></td>
    <td><%= link_to 'Show', group %></td>
    <td><%= link_to 'Edit', edit_group_path(group) %></td>
    <td><%= link_to 'Destroy', group, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<h1 class="center-text">Stats for <%= @group.name %></h1>
      <div class="statholder content-box">
				<div class="statbox4">
					<div class="stattitle">Average Score</div>
					<div class="statcontent">
						<span class="bignumber"><%= @group_average.to_i %></span>
					</div>
				</div>
				<div class="statbox4">
					<div class="stattitle">Group Wins/Losses</div>
					<div class="statcontent">
						<span class="bignumber"><%= @group_win %></span>/<%= @group_loss %>
					</div>
				</div>
				<div class="statbox4">
					<div class="stattitle">Members</div>
					<div class="statcontent">
						<span class="bignumber"><%= @group_size %></span>
					</div>
          <div style="clear:both;"></div>	
				</div>
        <div style="clear:both;"></div>
      </div>

<%= render "layouts/top25" %>