config/routes.rb
Masterater::Application.routes.draw do
  get "betas/confirmation"
  resources :betas, :only => ["new","create"]

  get "rankings/global"
  get "rankings/friends"
  get "rankings/groups"
  match "rankings" => "rankings#index"

  resources :groups, :only => ["show"]

  resources :users, :only => ["show"]                          #admin_data

  match "/settings" => "users#settings"
  get "user/show"
  get "user/update_info"

  match "/about" => "home#about"
  match "/privacy" => "home#privacy"
  match "/battle_update" => "home#battle_update"
  match "/invite" => "home#invite"
  match "/invite_update" => "home#invite_update"

  match "/canvas" => "home#canvas"

  match "/battle" => "home#battle"

  root :to => "home#index"

  match "/auth/:provider/callback" => "sessions#create"

  match "/signout" => "sessions#destroy", :as => :signout

end

app/views/layouts/_bottom-ad.html.erb
<!-- Begin: adBrite, Generated: 2011-03-06 0:43:31  -->
<script type="text/javascript">
var AdBrite_Title_Color = '0000FF';
var AdBrite_Text_Color = '000000';
var AdBrite_Background_Color = 'FFFFFF';
var AdBrite_Border_Color = 'CCCCCC';
var AdBrite_URL_Color = '008000';
try{var AdBrite_Iframe=window.top!=window.self?2:1;var AdBrite_Referrer=document.referrer==''?document.location:document.referrer;AdBrite_Referrer=encodeURIComponent(AdBrite_Referrer);}catch(e){var AdBrite_Iframe='';var AdBrite_Referrer='';}
</script>
<span style="white-space:nowrap;"><script type="text/javascript">document.write(String.fromCharCode(60,83,67,82,73,80,84));document.write(' src="http://ads.adbrite.com/mb/text_group.php?sid=1883732&zs=3732385f3930&ifr='+AdBrite_Iframe+'&ref='+AdBrite_Referrer+'" type="text/javascript">');document.write(String.fromCharCode(60,47,83,67,82,73,80,84,62));</script>
<a target="_top" href=""><img src="http://files.adbrite.com/mb/images/adbrite-your-ad-here-leaderboard.gif" style="background-color:#CCCCCC;border:none;padding:0;margin:0;" alt="Your Ad Here" width="14" height="90" border="0" /></a></span>
<!-- End: adBrite -->

app/views/layouts/_fb_general_invite.html.erb
<div id="fb-root"></div>
<script src="http://connect.facebook.net/en_US/all.js"></script>
<script>
  FB.init({
    appId  : <%= if Rails.env == 'production' then '107180036028128' else '171400646241780' end %>,
    status : true, // check login status
    cookie : true, // enable cookies to allow the server to access the session
    xfbml  : true  // parse XFBML
  });

document.observe("dom:loaded", function() {

  $$('.gen_invite').each(function(i) {i.on("click", function(event) {
      FB.ui({
        method: 'apprequests', 
        message: "Check out getFrankd! GetFrankd is a fun way to rate your friends' photos!", 
        title: 'Send out Requests for getFrankd'
      });
    });
  });
});
</script>

app/views/layouts/_top-ad.html.erb
<!-- Begin: adBrite, Generated: 2011-03-05 23:05:05  -->
<script type="text/javascript">
var AdBrite_Title_Color = '0000FF';
var AdBrite_Text_Color = '000000';
var AdBrite_Background_Color = 'FFFFFF';
var AdBrite_Border_Color = 'CCCCCC';
var AdBrite_URL_Color = '008000';
try{var AdBrite_Iframe=window.top!=window.self?2:1;var AdBrite_Referrer=document.referrer==''?document.location:document.referrer;AdBrite_Referrer=encodeURIComponent(AdBrite_Referrer);}catch(e){var AdBrite_Iframe='';var AdBrite_Referrer='';}
</script>
<span style="white-space:nowrap;"><script type="text/javascript">document.write(String.fromCharCode(60,83,67,82,73,80,84));document.write(' src="http://ads.adbrite.com/mb/text_group.php?sid=1883697&zs=3732385f3930&ifr='+AdBrite_Iframe+'&ref='+AdBrite_Referrer+'" type="text/javascript">');document.write(String.fromCharCode(60,47,83,67,82,73,80,84,62));</script>
<a target="_top" href=""><img src="http://files.adbrite.com/mb/images/adbrite-your-ad-here-leaderboard.gif" style="background-color:#CCCCCC;border:none;padding:0;margin:0;" alt="Your Ad Here" width="14" height="90" border="0" /></a></span>
<!-- End: adBrite -->

app/views/layouts/_top25.html.erb
<div class="content-box hotlist left">
<h2 class="center-text">Hottest Males</h2>
<table class="rankings">
  <tr>
    <th></th>
    <th></th>
    <th>Score</th>
    <th>Win</th>
    <th>Loss</th>
  </tr>

<% @top_males.each do |user| %>
  <tr>
    <td class="piccell cell"><%= link_to image_tag("http://graph.facebook.com/#{user.uid}/picture", :class=>"battle left"), user %> 
    <td class="name namecell cell"><%= link_to user.name.split(" ")[0], user %></td>
    <td class="numcell"><%= user.score.to_i %></td>
    <td class="numcell"><%= user.win %></td>
    <td class="numcell"><%= user.loss %></td
  </tr>
<% end %>
</table>
</div>

<div class="content-box hotlist right">
<h2 class="center-text">Hottest Females</h2>
<table class="rankings">
  <tr>
    <th></th>
    <th></th>
    <th>Score</th>
    <th>Win</th>
    <th>Loss</th>
  </tr>

<% @top_females.each do |user| %>
  <tr>
    <td class="piccell cell"><%= link_to image_tag("http://graph.facebook.com/#{user.uid}/picture", :class=>"battle left"), user %> 
    <td class="name namecell cell"><%= link_to user.name.split(" ")[0], user %></td>
    <td class="numcell"><%= user.score.to_i %></td>
    <td class="numcell"><%= user.win %></td>
    <td class="numcell"><%= user.loss %></td
  </tr>
<% end %>
</table>
</div>
<div style="clear:both;"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title>getFrankd</title>
  <%= stylesheet_link_tag "style" %>
  <%= stylesheet_link_tag "modalbox" %>
  <meta name="description" content="Rate how hot your facebook friends are to determine their Frank." />
  <meta name="keywords" content="beer, sports, basketball, football, hot girls, dating, singles, movies, video games, make up, cosmetics, weight loss, healthy, diet, shopping, discounts, deals, 
  celebrities, television shows, entertainment, travel, flight, cruise, airplane ticket, vacation, car rental, hotels, college students" />
  <link rel="image_src" href="images/logo.png" />
  <link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "modalbox", "builder" %>
  <%= csrf_meta_tag %>
  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-21824420-1']);
  _gaq.push(['_setDomainName', '.getFrankd.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>
		<% if current_user %>
  <div id="header">
	<div id="wrapper">
		<h1><%= link_to "getFrankd", battle_path, :class=>"no-dec" %></h1>
    <div id="social-butts">
    <a href="http://twitter.com/share" class="twitter-share-button" data-url="http://www.getFrankd.com" data-counturl="http://getFrankd.com/" data-text="I've been Frankd!" data-count="horizontal" data-via="getFrankd">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
    <iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fgetfrankd.com&amp;layout=button_count&amp;show_faces=false&amp;width=1&amp;action=like&amp;font=verdana&amp;colorscheme=light&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:100px; height:20px;" allowTransparency="true"></iframe>
    </div>
    <div id="right-nav">
		
    <%= link_to image_tag("http://graph.facebook.com/#{current_user.uid}/picture" , :class=>"left userimg"), current_user %>
    <ul>
   		<li><%= link_to current_user.name.split(" ")[0], current_user %></li>
			<li><%= link_to "Battle!", battle_path %></li>
			<li><%= link_to "Rankings", rankings_path %></li>
 <!--       <ul>
          <li>Global</li>
          <li>Friends</li>
          <li>Berkeley</li>
          <li>Le Bocage International School</li>
          <li>UC Berkeley</li>
        </ul>   -->
			<li><%= link_to "Sign Out", signout_path %></li>
		</ul>
		</div>
	</div>
  </div>
    <div id="content">

	<div id="wrapper">
  <div id="top-ad" class="banner-ad">
      <iframe id="top-ad-frame" width="750" height="98" src="" frameborder="0" scrolling="no" style="margin:0 auto; border:none;"></iframe>
  </div>
<%= yield %>
  </div>
  </div>
 <% else %>
 <%= yield %>
<% end %>
<% if current_user %>
  <div id="bottom-ad" class="banner-ad">
  <iframe id="bottom-ad-frame" width="750" height="98" src="" frameborder="0" scrolling="no"></iframe>
  </div>
<% end %>
  <a id="feedback" class="vertical-text tab feedback" href="/feedback.html" title="GetFrankd Feedback Form" onclick="
Modalbox.show(this.href, {title: this.title, width: 600}); return false;">Feedback</a>
  <%= link_to ("Invite Friends!", "/invite", :class => 'vertical-text tab gen_invite', :id => 'invites', :remote => true) %>
  <%= render 'layouts/fb_general_invite' %> 
  <div id="footer">
  <ul>
    <li><%= link_to("About", :controller=> "home", :action=> "about") %></li>
    <li><a href="mailto:contact@getfrankd.com">Contact Us</a></li>
    <li><%= link_to("Privacy", :controller=> "home", :action=> "privacy") %></li>
   </ul>
   <a href="http://mixpanel.com/?from=partner"><img src="http://mixpanel.com/site_media/images/mixpanel_partner_logo.gif" alt="Mobile Analytics by Mixpanel" /></a>
  </div>
<%= javascript_tag "$('top-ad-frame').src = '/ads/top-ad.html'; $('bottom-ad-frame').src = '/ads/bottom-ad.html';" %>
</body>
</html>

app/views/layouts/noad.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>getFrankd</title>
  <%= stylesheet_link_tag "style" %>
  <%= stylesheet_link_tag "modalbox" %>
  <meta name="description" content="Rate how hot your facebook friends are to determine their Frank." />
  <meta name="keywords" content="beer, sports, basketball, football, hot girls, dating, singles, movies, video games, make up, cosmetics, weight loss, healthy, diet, shopping, discounts, deals, 
  celebrities, television shows, entertainment, travel, flight, cruise, airplane ticket, vacation, car rental, hotels, college students" />
  <link rel="image_src" href="images/logo.png" />
  <link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "modalbox", "builder" %>
  <%= csrf_meta_tag %>
  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-21824420-1']);
  _gaq.push(['_setDomainName', '.getFrankd.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>
  <div id="header">
    <div id="wrapper">
	    <h1><%= link_to "getFrankd", root_path, :class=>"no-dec" %></h1>
      <div id="social-butts">
        <a href="http://twitter.com/share" class="twitter-share-button" data-url="http://www.getFrankd.com" data-counturl="http://getFrankd.com/" data-text="I've been Frankd!" data-count="horizontal" data-via="getFrankd">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
            <iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fgetfrankd.com&amp;layout=button_count&amp;show_faces=false&amp;width=1&amp;action=like&amp;font=verdana&amp;colorscheme=light&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:100px; height:20px;" allowTransparency="true"></iframe>
      </div>
	    <% if current_user %>      
        <div id="right-nav">
          <%= link_to image_tag("http://graph.facebook.com/#{current_user.uid}/picture" , :class=>"left userimg"), current_user %>
          <ul>
         		<li><%= link_to current_user.name.split(" ")[0], current_user %></li>
		        <li><%= link_to "Battle!", battle_path %></li>
		        <li><%= link_to "Rankings", rankings_path %></li>
		        <li><%= link_to "Sign Out", signout_path %></li>
	        </ul>
	      </div>
      <% end %>
    </div>
  </div>

  <div id="content">
    <div id="wrapper">
      <%= yield %>
    </div>
  </div>
  <a id="feedback-tab" href="/feedback.html" title="GetFrankd Feedback Form" onclick="
        Modalbox.show(this.href, {title: this.title, width: 600}); return false;"></a>

  <div id="footer">
    <ul>
      <li><%= link_to("About", :controller=> "home", :action=> "about") %></li>
      <li><a href="mailto:contact@getfrankd.com">Contact Us</a></li>
      <li><%= link_to("Privacy", :controller=> "home", :action=> "privacy") %></li>
    </ul>
     <a href="http://mixpanel.com/?from=partner"><img src="http://mixpanel.com/site_media/images/mixpanel_partner_logo.gif" alt="Mobile Analytics by Mixpanel" /></a>
  </div> 
</body>
</html>