config/routes.rb
Masterater::Application.routes.draw do
  get "betas/confirmation"
  resources :betas, :only => ["new","create"]

  get "rankings/global"
  get "rankings/friends"
  get "rankings/groups"
  match "rankings" => "rankings#index"

  resources :groups, :only => ["show"]

  resources :users, :only => ["show"]                          #admin_data

  match "/settings" => "users#settings"
  get "user/show"
  get "user/update_info"

  match "/about" => "home#about"
  match "/privacy" => "home#privacy"
  match "/battle_update" => "home#battle_update"
  match "/invite" => "home#invite"
  match "/invite_update" => "home#invite_update"

  match "/canvas" => "home#canvas"

  match "/battle" => "home#battle"

  root :to => "home#index"

  match "/auth/:provider/callback" => "sessions#create"

  match "/signout" => "sessions#destroy", :as => :signout

end

app/models/beta.rb
class Beta < ActiveRecord::Base
end

app/controllers/betas_controller.rb
class BetasController < ApplicationController
  skip_before_filter :authenticate, :only =>["new", "create", "confirmation"]
  # GET /betas
  # GET /betas.xml
  def index
    @betas = Beta.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @betas }
    end
  end

  # GET /betas/1
  # GET /betas/1.xml
  def show
    @beta = Beta.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @beta }
    end
  end

  # GET /betas/new
  # GET /betas/new.xml
  def new
    @beta = Beta.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @beta }
    end
  end

  # GET /betas/1/edit
  def edit
    @beta = Beta.find(params[:id])
  end

  # POST /betas
  # POST /betas.xml

  def confirmation
    respond_to do |format|
      format.html
    end
  end  

  def create
    @beta = Beta.new(params[:beta])
    if Beta.find_by_email(@beta.email) then
      redirect_to :action=>"confirmation"
      return
    end
    @beta.uid = session[:uid]
    @beta.access = (@beta.email == "frankenmasturbattle_#{session["uid"]}")

    respond_to do |format|
      if @beta.save
        format.html { redirect_to(:action=>"confirmation", :notice => 'Beta was successfully created.') }
        format.xml  { render :xml => @beta, :status => :created, :location => @beta }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @beta.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /betas/1
  # PUT /betas/1.xml
  def update
    @beta = Beta.find(params[:id])

    respond_to do |format|
      if @beta.update_attributes(params[:beta])
        format.html { redirect_to(@beta, :notice => 'Beta was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @beta.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /betas/1
  # DELETE /betas/1.xml
  def destroy
    @beta = Beta.find(params[:id])
    @beta.destroy

    respond_to do |format|
      format.html { redirect_to(betas_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/betas_helper.rb
module BetasHelper
end

app/views/betas/_form.html.erb
<%= form_for(@beta) do |f| %>
  <% if @beta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beta.errors.count, "error") %> prohibited this beta from being saved:</h2>

      <ul>
      <% @beta.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uid %><br />
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :access %><br />
    <%= f.check_box :access %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/betas/confirmation.html.erb
<br>Your request has been sent. Please check your email for further instructions.</br>

app/views/betas/edit.html.erb
<h1>Editing beta</h1>

<%= render 'form' %>

<%= link_to 'Show', @beta %> |
<%= link_to 'Back', betas_path %>

app/views/betas/index.html.erb
<h1>Listing betas</h1>

<table>
  <tr>
    <th>Uid</th>
    <th>Email</th>
    <th>Access</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @betas.each do |beta| %>
  <tr>
    <td><%= beta.uid %></td>
    <td><%= beta.email %></td>
    <td><%= beta.access %></td>
    <td><%= link_to 'Show', beta %></td>
    <td><%= link_to 'Edit', edit_beta_path(beta) %></td>
    <td><%= link_to 'Destroy', beta, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Beta', new_beta_path %>

app/views/betas/new.html.erb
<h1>Beta Signup</h1>

getFrankd is currently undergoing closed beta testing. Please submit your email address so we can let you know when to join! </br>
<%= form_for(@beta) do |f| %>
  <% if @beta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beta.errors.count, "error") %> prohibited this beta from being saved:</h2>

      <ul>
      <% @beta.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit 'Request invite' %>
  </div>
<% end %>

app/views/betas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Uid:</b>
  <%= @beta.uid %>
</p>

<p>
  <b>Email:</b>
  <%= @beta.email %>
</p>

<p>
  <b>Access:</b>
  <%= @beta.access %>
</p>


<%= link_to 'Edit', edit_beta_path(@beta) %> |
<%= link_to 'Back', betas_path %>